-- AlterTable
ALTER TABLE "BotRunnerHeartbeat" ADD COLUMN     "endedAt" TIMESTAMP(3),
ADD COLUMN     "leaseVer" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
