-- AlterTable
ALTER TABLE "StrategyConfig" ADD COLUMN     "adxConfirmThreshold" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "atrConfirmPeriod" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN     "donchianLookback" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "donchianNearBreakPct" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
ADD COLUMN     "minAtrPct" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "rangeFollowTrendOnly" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "rangeMinAtrMult" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "supertrendMult" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "supertrendPeriod" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "trendSlopeThresholdAbs" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
ADD COLUMN     "trendSlopeWindow" INTEGER NOT NULL DEFAULT 30;
