-- AlterTable
ALTER TABLE "StrategyConfig" ADD COLUMN     "defaultSize" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "entryForwardEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "leverage" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "martinMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "martinOnLossWebsea" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxSize" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "targetProfit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "timeframe" "Timeframe" NOT NULL DEFAULT '5m',
ADD COLUMN     "useMartin" BOOLEAN NOT NULL DEFAULT false;
